name: glow
description: E-learning Platform.
version: 1.0.0+1

environment:
   sdk: '>=2.1.0 <3.0.0'

dependencies:
   flutter:
      sdk: flutter
   cupertino_icons: ^0.1.2
   localstorage: ^3.0.1+4
   video_player: ^0.10.5+2
   dotted_border: ^1.0.5
   http: ^0.12.0+2
   dio: ^3.0.9
   provider: ^3.1.0
   intl: ^0.15.8
   lottie: ^0.3.3
   get_it: ^4.0.2
   pinput: ^0.2.0
   image_picker: ^0.6.0+15
   file_picker: ^1.11.0
   path_provider: ^1.5.1
   device_preview: ^0.4.4
   flutter_pdfview: ^1.0.2+3
   shared_preferences: ^0.5.7

dev_dependencies:
   flutter_test:
      sdk: flutter
flutter:
   uses-material-design: true
   assets:
      - assets/pngs/
      - assets/lotties/

   fonts:
      - family: Overpass-Regular
        fonts:
           - asset: assets/fonts/Overpass-Regular.ttf
